FROM node:4.4

RUN mkdir -p /root/.ssh
ADD id_rsa /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts

RUN git clone -b {{ .BRANCH }} git@github.com:{{ .REPO_OWNER }}/{{ .REPO_NAME }}.git
RUN cd {{ .REPO_NAME }} && git checkout {{ .HASH }}

ENV NPM_CONFIG_LOGLEVEL warn
ENV NODE_ENV=production

RUN npm install -g npm@3

RUN cd {{ .REPO_NAME }} && npm install
RUN cd {{ .REPO_NAME }} && npm run build
